version: '3.8'
services:
  db:
    image: mariadb:10.6.5
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: illustrator2
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - ./back/config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/var/www/html
      - ./localhost.crt:/etc/ssl/certs/localhost.crt
      - ./localhost.key:/etc/ssl/private/localhost.key
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ''
      DB_NAME: illustrator2

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/var/www/html
      - ./localhost.crt:/etc/ssl/certs/localhost.crt
      - ./localhost.key:/etc/ssl/private/localhost.key
    ports:
      - 80:80
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: ''
    ports:
      - 8081:80
    depends_on:
      - db

volumes:
  db_data: {}